### ISSUE TITLE
Cut with two planes

### ISSUE THREAD

**Issue by shalinsirwani** [hroncok/stlcut#1]
possible to cut with two planes like this :-
![1](https://user-images.githubusercontent.com/28221425/106584766-996f1780-656c-11eb-88ed-c41f9e7cb9a7.jpg)

then specifically  deciding sides like this:-
![1](https://user-images.githubusercontent.com/28221425/106584875-b7d51300-656c-11eb-9a86-213b648745dc.jpg)

**Comment by hroncok** [comment]
Not possible with this code.
